### PR TITLE
Add speakers

### PR DESCRIPTION
**Pull request by DeveloperAlly**

### CODE REVIEW

**Comment by 2color** [comment]
Looks good. For them to appear you also need to update devent.toml as follows: 
https://github.com/pathfindertools/ipfs-camp-2022/blob/33fab1895fd65d29857d91ec3d49382e1b111e60/devent.toml#L162-L166

**Comment by mishmosh** [comment]
Can you make the devent.toml file as @2color describes? Otherwise, the images will be added to the repo, but won't be rendered on the site. Thanks!

**Comment by DeveloperAlly** [comment]
Sorry just saw this... yep

**Comment by mishmosh** [comment]
Build preview is showing blanks for images, looking into it...

**Comment by DeveloperAlly** [comment]
Odd. 

> Build preview is showing blanks for images, looking into it...

Odd.. I can't see anything different in the toml to others.
Only thing I can think to check is the reference links

**Comment by mishmosh** [comment]
Ah, 2 things:
- filenames use underscores, but toml uses hyphens (dave_montali vs. dave-motali). for consistency's sake with existing files, probably best to rename the files.
- Can you remove the extra space at beginning of lines 572-630?

**Comment by DeveloperAlly** [comment]
ahh yea copy pasted Daniels example. Fixed files

**Comment by mishmosh** [comment]
Ah, there are now 2 copies of every image file.
- Build preview looks good, so I'm merging this now to get this live and keep things moving.
- Please submit a followup PR to delete the underscore versions.

**Pull request merged**
